export const USER_INIT = "USER_INIT";

export const USER = {
  GET_USER: "OAUTH__GET_USER",
  SET_USER: "OAUTH__SET_USER",
  LOAD_USER: "OAUTH__LOAD_USER"
};

export const OAUTH = {
  SET_TOKEN: "OAUTH__SET_TOKEN",
  GET_TOKEN: "OAUTH__GET_TOKEN",
  CLEAR_TOKEN: "OAUTH__CLEAR_TOKEN"
};

export const DISK = {
  INIT_DATA: "DISK__INIT_DATA",
  INIT_FOLDER: "DISK__INIT_FOLDER",
  SET_DATA: "DISK__SET_DATA",
  SET_FOLDER_DATA: "DISK__SET_FOLDER_DATA",
  SET_CURRENT_FOLDER: "DISK__SET_CURRENT_FOLDER",
  LOADING_DATA: "DISK__LOADING_DATA"
};
